spring:
  application:
    name: mmall-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/goofyww/mmall-config-repo.git
          username: goofyww
          password: *
          basedir: H:\ideaProjects\mmall-config-repo
  rabbitmq:
    host: www.oecoo.com
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/,http://localhost:8763/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
